{"uuid": "73fcbd50-7f2e-4a12-a5de-19b8791f2da3", "children": ["0517ccb6-7a80-4fe8-99e9-5f949554e62c"], "befores": [{"name": "test", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: An element could not be located on the page using the given search parameters.\n\n", "trace": "  File \"d:\\python\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"d:\\python\\lib\\site-packages\\_pytest\\fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"d:\\python\\lib\\site-packages\\_pytest\\fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\Python\\PyCharm Community Edition 2019.2.3\\A+6.0 project\\case\\test_person.py\", line 18, in test\n    myPerson(driver).login_y_n()\n  File \"D:\\Python\\PyCharm Community Edition 2019.2.3\\A+6.0 project\\page\\page_my\\person.py\", line 71, in login_y_n\n    myPerson.get_id(self, self.family_list_button1).click()\n  File \"D:\\Python\\PyCharm Community Edition 2019.2.3\\A+6.0 project\\common\\public.py\", line 41, in get_id\n    return self.driver.find_element_by_id(id)\n  File \"d:\\python\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 360, in find_element_by_id\n    return self.find_element(by=By.ID, value=id_)\n  File \"d:\\python\\lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 276, in find_element\n    'value': value})['value']\n  File \"d:\\python\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"d:\\python\\lib\\site-packages\\appium\\webdriver\\errorhandler.py\", line 29, in check_response\n    raise wde\n  File \"d:\\python\\lib\\site-packages\\appium\\webdriver\\errorhandler.py\", line 24, in check_response\n    super(MobileErrorHandler, self).check_response(response)\n  File \"d:\\python\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1614671570111, "stop": 1614671600400}], "start": 1614671570111, "stop": 1614671600442}